# pylint: disable=line-too-long
"""
SHA-256 registry of the large example data files.

Generated by: python -m rattlesnake.data.registry
Do not edit by hand. Run the command above to regenerate this file.

Each key is a file name relative to src/rattlesnake/examples/.
Each value is the SHA-256 hash of that file.
"""

registry = {
    "hardware/sdynpy_system/sdynpy_system.npz": "3d7028f829c0e77896ce3b74bf210e0bcdb0b1ff3aa5beab54ada0f6c065842b",
}
