# pylint: disable=line-too-long
"""
SHA-256 registry of the large example data files.

Generated by: python -m rattlesnake.data.registry
Do not edit by hand. Run the command above to regenerate this file.

Each key is a file name relative to src/rattlesnake/examples/.
Each value is the SHA-256 hash of that file.
"""

registry = {
    "environment/modal/modal_v3.nc4": "f202a695c6242671f986b742933b552f41c44bfb5fb83a4fce516c56daadc8af",
    "environment/modal/modal_v4.nc4": "d57b160a852d22651b70d741b06a95bf1e05ebc57bd25224e13411d126038049",
    "environment/random/random_control_data.nc4": "21e6e9255033569b6a8143afab6b81ecfdd7028e5ba2a9bcac5704c62fbebf6a",
    "environment/random/random_spec.npz": "645afecee211fc54a53cc8c8bc410185eb025b9d536d945692dc834d95e8536f",
    "environment/random/random_v3.nc4": "6e917101aca2ccf2726e6c45e86ca9256cf3206a28d4ac2f130cf3e6d38ba0b3",
    "environment/random/random_v4.nc4": "ec853199983d857777da3c03dbced95706da5e25b0e6aea57b9d35844a60a0cd",
    "environment/read/read_v4.nc4": "7feb09f4e2a843538b35e20ecd746dd6036b7a0597be8f7771983a566bc67423",
    "environment/sds/sds_spec.npz": "699f501b5247d15300e62c8f738052060352952c8435cdac8060ba27f5a84aa1",
    "environment/sds/sds_v4.nc4": "09f03945ef4fe864faea09fcac5be80afa675ac619f1c3682926157b49ae126e",
    "environment/sine/sine_control_data.npz": "ed6e8681d42fa6cb7333dca978067eb3a8fc97cf7e92b39aa7fd256407d0413c",
    "environment/sine/sine_spec.npz": "76dbba31baf26d7fa4166d01c1457eacf8b1dbe95835f6c903fde4729fca547e",
    "environment/sine/sine_v3.nc4": "dca1efe30dfef5a94f7430f3f26d0d217aebf08216fa2c5078b7a94ef0daf9a0",
    "environment/sine/sine_v4.nc4": "85bcff3ff94a4e7d1fe70e822f37ecba3a6cf9e12e05a8f27ef2b76551201fad",
    "environment/skeleton/skeleton_v4.nc4": "34ed9ed8a5d5267b5461cdff3a1e922781b47321b0db9a903e1b8c9214ad9889",
    "environment/sysid/sysid.nc4": "3a877e426d012fafbf30a6f4798cd38e276bdc96e211f78e779ad009581805b6",
    "environment/sysid/sysid_data.nc4": "c276ef463e7bb1b58244c027496d3e17833b0bb4b63dfc296a7f2f9327831580",
    "environment/time/time_signal.npy": "c27ae4abd1cfeba86f335f259788e79fec63720732f64ee4622bf02be8bdc6b8",
    "environment/time/time_v3.nc4": "b31687e2a447d8f25218a11645ec5a4cd9a4e74817c75362ab18913e74b732af",
    "environment/time/time_v4.nc4": "f7bdaa9b18ff92e053d43f720e47644562eb15aa6afcccb3df384bedd25e928c",
    "environment/transient/transient_signal.npy": "325fabf3b36acd84011aa14b4dace06189338519954dc4142d9fc522c62bec14",
    "environment/transient/transient_v3.nc4": "bad6c0a25b78d5ee690533c4329884cfd26c26734cf32e52a53caeed4a704d87",
    "environment/transient/transient_v4.nc4": "b58ef79d6a553a070ad6cf9fbf34d07ee9114229b0277dda710801d00ce8d8af",
    "frame_wing/data/random_vibration_specification.npz": "f402fe4f1320cf1e1f8259c8505ecc834e713eda61288a035136bb358b29aa1d",
    "frame_wing/data/rattlesnake_state_space_system.npz": "d25349265b06190e4de76565b5a2b4f50d7c2fccd07f66f609a03072433137ab",
    "frame_wing/data/sdynpy_fem_geometry.npz": "c0131043c23b129b0f3947327ad9efa02fb56b4c8a22acfdfb514d22b028e6cd",
    "frame_wing/data/sdynpy_fem_shapes.npy": "c2c37c8ae8fbdbb4ee32576541b881ed8a53edb2f65adec364b354bbc436beb5",
    "frame_wing/data/sdynpy_test_geometry.npz": "b75342725c75599abad632dfa74ed95fb0fc6754fb68fbb88d1ddc15bfefecc4",
    "frame_wing/data/sine_specification.npz": "1a7c7d9abb811c0b7e4f5f34c599d93fc20c3891599824a57807dfc2ea98c337",
    "frame_wing/data/srs_specification.npz": "bebe8dec134ebdb6f7e2357cb1740dcca3130ae1442b1c77d16986147c33c361",
    "frame_wing/data/transient_specification.npz": "3bd85c7470670baf56d1de7c62bc60b95097d6a008231d12a0b3a9fb84f186c0",
    "hardware/exodus/exodus_v3.nc4": "579e5d829fa4297fefbc303600e5b2c49031b4122358b5a48d9ce47f9a6b9f1f",
    "hardware/exodus/exodus_v4.nc4": "480da561dc499843b4bce06a0b5b47bbf407e78fec9ed97000f147f8e947ad62",
    "hardware/sdynpy_frf/sdynpy_frf.npz": "524c2c74d91e291df287808d279fc58e8896b5e7454ddfdd4b6b720e263981cb",
    "hardware/sdynpy_frf/sdynpy_frf_v3.nc4": "635166f878acc53c9a3a18b42f2ba5f7dd81b0a06e9fa33db65529b510b94068",
    "hardware/sdynpy_frf/sdynpy_frf_v4.nc4": "b7c18797040f25ad071879ca4bb100b1b2c130ca29023a25cdc8f923dcabe3ba",
    "hardware/sdynpy_system/sdynpy_system.npz": "3d7028f829c0e77896ce3b74bf210e0bcdb0b1ff3aa5beab54ada0f6c065842b",
    "hardware/sdynpy_system/sdynpy_system_v3.nc4": "f202a695c6242671f986b742933b552f41c44bfb5fb83a4fce516c56daadc8af",
    "hardware/sdynpy_system/sdynpy_system_v4.nc4": "ec853199983d857777da3c03dbced95706da5e25b0e6aea57b9d35844a60a0cd",
    "hardware/state_space/state_space.npz": "20e0265ce67d57b9fcf90ccf66cff9fad1a216864a67ff015a064ea07a2e7146",
    "hardware/state_space/state_space_v3.nc4": "b85a7b716b1f82b348cb958b99d072ea9245d1f6caef363bffe69ce85c072768",
    "hardware/state_space/state_space_v4.nc4": "1a69c9ee362003074a56d1007a42a472fc7325d4def1234a797d5e9918c88436",
}
