"""
Generate ``_registry.py``, the SHA-256 registry of large example data files.

The generator walks the examples directory and hashes every file whose suffix
is in ``SUFFIXES``. It writes a ``registry`` dictionary that maps each name to
its hash, sorted by name. Run it from the repository root after any data file
is added, removed, or changed::

    uv run python -m rattlesnake.data.registry
    uv run python -m rattlesnake.data.registry --check

The first command rewrites ``_registry.py`` and replaces its whole content. The
second command leaves the file alone. It prints the differences and exits with
status 1 when ``_registry.py`` is stale.

The generated text already follows ``ruff format``, so formatting the file
produces no diff. Each entry stays on one line because ruff cannot split a
string. The header disables pylint's ``line-too-long`` check for that reason, and
its module docstring satisfies pylint's ``missing-module-docstring`` check.

``SUFFIXES`` must match the ``exclude`` globs in ``pyproject.toml``. A suffix
that is excluded from the wheel but missing here is a file that ships nowhere.

Attributes
----------
SUFFIXES : tuple of str
    File suffixes that belong in the registry.
HEADER : str
    Pylint directive and module docstring at the top of the generated file.
REGISTRY_PATH : pathlib.Path
    The ``_registry.py`` file that sits next to this module on disk.
"""

import argparse
import ast
import json
import os
import pathlib
import sys

from rattlesnake import data

SUFFIXES = (".nc4", ".npz", ".npy")
HEADER = (
    "# pylint: disable=line-too-long\n"
    '"""\n'
    "SHA-256 registry of the large example data files.\n"
    "\n"
    "Generated by: python -m rattlesnake.data.registry\n"
    "Do not edit by hand. Run the command above to regenerate this file.\n"
    "\n"
    "Each key is a file name relative to src/rattlesnake/examples/.\n"
    "Each value is the SHA-256 hash of that file.\n"
    '"""\n'
    "\n"
)
REGISTRY_PATH = pathlib.Path(data.__file__).with_name("_registry.py")


def file_list(
    *,
    directory: str | os.PathLike[str],
    suffixes: tuple[str, ...] = SUFFIXES,
) -> list[str]:
    """
    List the files under a directory that have one of the given suffixes.

    Parameters
    ----------
    directory : str or os.PathLike
        Directory to search, including all subdirectories.
    suffixes : tuple of str, optional
        File suffixes to keep, with the leading dot. Defaults to ``SUFFIXES``.

    Returns
    -------
    list of str
        Names relative to ``directory``, with ``/`` separators on every
        platform, sorted alphabetically.

    Raises
    ------
    FileNotFoundError
        If ``directory`` is not a directory.
    """
    directory = pathlib.Path(directory)
    if not directory.is_dir():
        raise FileNotFoundError(f"not a directory: {directory}")
    return sorted(
        path.relative_to(directory).as_posix()
        for path in directory.rglob("*")
        if path.is_file() and path.suffix in suffixes
    )


def build(
    *,
    directory: str | os.PathLike[str] | None = None,
    suffixes: tuple[str, ...] = SUFFIXES,
) -> dict[str, str]:
    """
    Hash the data files under a directory.

    Parameters
    ----------
    directory : str or os.PathLike, optional
        Directory to search. Defaults to ``data.PACKAGE_DIRECTORY``.
    suffixes : tuple of str, optional
        File suffixes to register. Defaults to ``SUFFIXES``.

    Returns
    -------
    dict of str to str
        File name to SHA-256 hash, in sorted name order.
    """
    if directory is None:
        directory = data.PACKAGE_DIRECTORY
    directory = pathlib.Path(directory)
    return {
        name: data.hash_compute(path=directory / name)
        for name in file_list(directory=directory, suffixes=suffixes)
    }


def render(*, entries: dict[str, str]) -> str:
    """
    Format a registry as the source text of ``_registry.py``.

    Parameters
    ----------
    entries : dict of str to str
        File name to SHA-256 hash.

    Returns
    -------
    str
        ``HEADER`` followed by a ``registry`` dictionary with one line per
        entry. An empty registry is ``registry = {}``, which is how ruff
        formats it.
    """
    if not entries:
        return HEADER + "registry = {}\n"
    lines = [
        f"    {json.dumps(name)}: {json.dumps(digest)},\n"
        for name, digest in entries.items()
    ]
    return HEADER + "registry = {\n" + "".join(lines) + "}\n"


def generate(
    *,
    directory: str | os.PathLike[str] | None = None,
    suffixes: tuple[str, ...] = SUFFIXES,
) -> str:
    """
    Build the source text of ``_registry.py`` from the files on disk.

    Parameters
    ----------
    directory : str or os.PathLike, optional
        Directory to search. Defaults to ``data.PACKAGE_DIRECTORY``.
    suffixes : tuple of str, optional
        File suffixes to register. Defaults to ``SUFFIXES``.

    Returns
    -------
    str
        The text from ``render`` for the files that ``build`` finds.
    """
    return render(entries=build(directory=directory, suffixes=suffixes))


def read(*, path: str | os.PathLike[str]) -> dict[str, str]:
    """
    Read the ``registry`` dictionary from a generated file without running it.

    Parameters
    ----------
    path : str or os.PathLike
        Path of a file such as ``_registry.py``.

    Returns
    -------
    dict of str to str
        The literal value assigned to ``registry``.

    Raises
    ------
    ValueError
        If the file assigns no literal ``registry`` dictionary of strings.
    """
    tree = ast.parse(pathlib.Path(path).read_text(encoding="utf-8"))
    for node in tree.body:
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "registry"
        ):
            value = ast.literal_eval(node.value)
            if isinstance(value, dict) and all(
                isinstance(key, str) and isinstance(item, str)
                for key, item in value.items()
            ):
                return value
    raise ValueError(f"{path} does not assign a registry dictionary of strings")


def difference_list(*, current: dict[str, str], generated: dict[str, str]) -> list[str]:
    """
    Describe how a registry differs from a freshly built one.

    Parameters
    ----------
    current : dict of str to str
        Registry in the existing ``_registry.py``.
    generated : dict of str to str
        Registry from ``build``.

    Returns
    -------
    list of str
        One line per difference, sorted by file name. A line starts with
        ``missing`` for a file on disk that the registry lacks, ``stale`` for a
        registry entry whose file is gone, or ``changed`` for a different hash.
        The list is empty when the registries match.
    """
    differences = []
    for name in sorted(current.keys() | generated.keys()):
        if name not in current:
            differences.append(f"missing  {name}")
        elif name not in generated:
            differences.append(f"stale    {name}")
        elif current[name] != generated[name]:
            differences.append(f"changed  {name}")
    return differences


def main(argv: list[str] | None = None) -> int:
    """
    Write ``_registry.py``, or check it with ``--check``.

    The command line accepts three options. ``--directory`` names the folder to
    search and defaults to the examples package. ``--output`` names the file to
    write or check and defaults to the ``_registry.py`` next to this module.
    ``--check`` compares instead of writing.

    Parameters
    ----------
    argv : list of str, optional
        Command-line arguments. Defaults to ``sys.argv[1:]``.

    Returns
    -------
    int
        0 after a write, or after a check that finds no differences. 1 after a
        check that finds differences. 2 if the search directory is missing.
    """
    parser = argparse.ArgumentParser(
        description="Generate _registry.py for the large example data files."
    )
    parser.add_argument("--directory", type=pathlib.Path, default=None)
    parser.add_argument("--output", type=pathlib.Path, default=REGISTRY_PATH)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        generated = build(directory=args.directory)
    except FileNotFoundError as error:
        print(error, file=sys.stderr)
        return 2

    if not args.check:
        args.output.write_text(render(entries=generated), encoding="utf-8")
        print(f"Wrote {len(generated)} entries to {args.output}")
        return 0

    current = read(path=args.output) if args.output.exists() else {}
    differences = difference_list(current=current, generated=generated)
    for line in differences:
        print(line)
    if differences:
        print(f"{args.output} is stale. Run: python -m rattlesnake.data.registry")
        return 1
    print(f"{args.output} is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
