# -*- coding: utf-8 -*-
"""
This file defines a Time Signal Generator environment where a signal can be
loaded and played directly to the output devices.  This is perhaps the simplest
control type that might be implemented by the controller, so start here when
designing new control types.

Rattlesnake Vibration Control Software
Copyright (C) 2021  National Technology & Engineering Solutions of Sandia, LLC
(NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the U.S.
Government retains certain rights in this software.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import copy
from enum import Enum
import multiprocessing as mp
import multiprocessing.queues as mpqueue
import queue as thqueue
from typing import List

import netCDF4 as nc4
import numpy as np
import openpyxl
from qtpy import QtCore, QtWidgets, uic

from rattlesnake.environment.abstract_environment import (
    Environment,
    EnvironmentCommands,
    EnvironmentInstructions,
    EnvironmentMetadata,
)
from rattlesnake.environment.environment_utilities import EnvironmentType
from rattlesnake.hardware.abstract_hardware import HardwareMetadata
from rattlesnake.user_interface.ui_utilities import UICommands
from rattlesnake.utilities import (
    load_time_history,
    db2scale,
    GlobalCommands,
    RattlesnakeError,
    VerboseMessageQueue,
)

CONTROL_TYPE = EnvironmentType.TIME
TEST_LEVEL_THRESHOLD = 1.01


# region Commands
class TimeCommands(EnvironmentCommands):
    SET_TEST_LEVEL = 0
    SET_REPEAT = 1
    SET_NO_REPEAT = 2

    VALID_PROFILE_COMMANDS = (
        SET_TEST_LEVEL,
        SET_REPEAT,
        SET_NO_REPEAT,
    )
    VALID_DATA = {
        SET_TEST_LEVEL: int,
        SET_REPEAT: type(None),
        SET_NO_REPEAT: type(None),
    }


class TimeUICommands(Enum):
    TIME_DATA = 0


# endregion


# region: Metadata
class TimeMetadata(EnvironmentMetadata):
    """Storage container for parameters used by the Time Environment"""

    def __init__(
        self,
        environment_name: str = "Time",
        channel_list_bools: list = [],
        sample_rate: int = None,
        output_signal: np.array = None,
        cancel_rampdown_time: float = None,
    ):
        """
        Container to hold signal processing parameters for the Time environment

        Parameters
        ----------
        sample_rate : int
            Number of samples per second that the controller runs. This value
            dictates the sample length, not the hardware itself. Should match
            hardware but not catastrophic if it doesn't
        output_signal : np.ndarray
            Signal that will be generated by the sources, 2D array (n_outputs x
            n_samples)
        cancel_rampdown_time : float
            Time used to decay the signal to zero if the environment is stopped.
            Prevents "hard stops" from damaging equipment.

        """
        super().__init__(
            CONTROL_TYPE, environment_name, channel_list_bools, sample_rate
        )
        self.output_signal = output_signal
        self.cancel_rampdown_time = cancel_rampdown_time
        self._signal_file = None  # This is only used for saving purposes

    @property
    def signal_samples(self):
        """The number of samples in the signal"""
        return self.output_signal.shape[-1]

    @property
    def output_channels(self):
        """The number of output channels in the signal"""
        return self.output_signal.shape[0]

    @property
    def signal_time(self):
        """The length of the signal in seconds"""
        return self.signal_samples / self.sample_rate

    @property
    def cancel_rampdown_samples(self):
        """The number of samples required to ramp down the signal when cancelled"""
        return int(self.cancel_rampdown_time * self.sample_rate)

    @property
    def signal_file(self):
        return self._signal_file

    def set_file(self, filepath):
        self._signal_file = filepath

    # endregion

    # region Validation
    def validate(self, hardware_metadata):
        # Prevent duplicate entries
        super().validate(hardware_metadata)

        if (
            not isinstance(self.cancel_rampdown_time, (int, float))
            or self.cancel_rampdown_time <= 0
        ):
            raise RattlesnakeError(
                f"{self.environment_name} cancel_rampdown_time must be a number greater than 0"
            )

        if not isinstance(self.sample_rate, int) or self.sample_rate <= 0:
            raise RattlesnakeError(
                f"{self.environment_name} sample_rate must be a number greater than 0"
            )

        if not isinstance(self.output_signal, np.ndarray):
            raise RattlesnakeError(
                f"{self.environment_name} output_singal must be a 2D numpy array"
            )

        if self.output_signal.ndim != 2:
            raise RattlesnakeError(
                f"{self.environment_name} output_signal must be a 2D numpy array"
            )

        environment_channels = [
            channel
            for channel, channel_bool in zip(
                hardware_metadata.channel_list, self.channel_list_bools
            )
            if channel_bool
        ]
        num_output_channels = len(
            [channel for channel in environment_channels if channel.is_output_channel()]
        )
        num_output = self.output_signal.shape[0]
        if num_output != num_output_channels:
            raise RattlesnakeError(
                f"{self.environment_name}, {num_output} signals defined for {num_output_channels} channels"
            )

        return True

    # endregion

    # region Loading
    def save_metadata_to_netcdf(
        self,
        netcdf_group_handle: nc4._netCDF4.Group,  # pylint: disable=c-extension-no-member
    ):
        """
        Stores parameters to a netCDF group so they can be recovered.

        Parameters
        ----------
        netcdf_group_handle : nc4._netCDF4.Group
            Reference to the netCDF4 group in which the environment data should
            be stored.

        """
        netcdf_group_handle.cancel_rampdown_time = self.cancel_rampdown_time
        # Save the output signal
        netcdf_group_handle.createDimension("output_channels", self.output_channels)
        netcdf_group_handle.createDimension("signal_samples", self.signal_samples)
        var = netcdf_group_handle.createVariable(
            "output_signal", "f8", ("output_channels", "signal_samples")
        )
        var[...] = self.output_signal

    @classmethod
    def load_metadata_from_netcdf(
        cls,
        group: nc4._netCDF4.Dataset,
        environment_name: str,
        channel_list_bools: List[bool],
        hardware_metadata: HardwareMetadata,
    ):  # pylint: disable=c-extension-no-member
        """Collects environment parameters from a netCDF dataset.

        This function retrieves parameters from a netCDF dataset that was written
        by the controller during streaming.  It must populate the widgets
        in the user interface with the proper information.

        This function is the "read" counterpart to the store_to_netcdf
        function in the TimeParameters class, which will write
        parameters to the netCDF file to document the metadata.

        Note that the entire dataset is passed to this function, so the function
        should collect parameters pertaining to the environment from a Group
        in the dataset sharing the environment's name, e.g.

        ``group = netcdf_handle.groups[self.environment_name]``
        ``self.definition_widget.parameter_selector.setValue(group.parameter)``

        Parameters
        ----------
        netcdf_handle : nc4._netCDF4.Dataset :
            The netCDF dataset from which the data will be read.  It should have
            a group name with the enviroment's name.
        """
        output_signal = group.variables["output_signal"][...].data
        cancel_rampdown_time = group.cancel_rampdown_time

        return cls(
            environment_name,
            channel_list_bools,
            hardware_metadata.sample_rate,
            output_signal,
            cancel_rampdown_time,
        )

    @staticmethod
    def create_blank_worksheet_template(worksheet):
        worksheet.cell(1, 1, "Control Type")
        worksheet.cell(1, 2, "Time")
        worksheet.cell(
            1,
            4,
            "Note: Replace cells with hash marks (#) to provide the requested parameters.",
        )
        worksheet.cell(2, 1, "Signal File")
        worksheet.cell(
            2, 3, "# Path to the file that contains the time signal that will be output"
        )
        worksheet.cell(3, 1, "Cancel Rampdown Time")
        worksheet.cell(
            3,
            3,
            "# Time for the environment to ramp to zero if the environment is cancelled.",
        )

    def save_metadata_to_worksheet(
        self, worksheet: openpyxl.worksheet.worksheet.Worksheet
    ):
        super().store_to_worksheet(worksheet)

        if self.signal_file:
            worksheet.cell(2, 2, str(self.signal_file))
        if self.cancel_rampdown_time is not None:
            worksheet.cell(3, 2, str(self.cancel_rampdown_time))

    @classmethod
    def load_metadata_from_worksheet(
        cls,
        worksheet: openpyxl.worksheet.worksheet.Worksheet,
        environment_name: str,
        channel_list_bools: List[bool],
        hardware_metadata: HardwareMetadata,
    ):
        for row in worksheet.rows:
            name = str(row[0].value).lower().strip().replace(" ", "_")
            value = row[1].value
            match name:
                case "control_type":
                    continue
                case "signal_file":
                    signal_file = value
                    output_signal = load_time_history(
                        signal_file, hardware_metadata.sample_rate
                    )
                case "cancel_rampdown_time":
                    cancel_rampdown_time = float(value)
                case "":
                    continue
                case _:
                    raise RattlesnakeError(
                        f"{name} does not go with {CONTROL_TYPE} environment"
                    )

        metadata = cls(
            environment_name,
            channel_list_bools,
            hardware_metadata.sample_rate,
            output_signal,
            cancel_rampdown_time,
        )
        if signal_file:
            metadata.set_file(signal_file)

        return metadata

    # endregion


# region Instructions
class TimeInstructions(EnvironmentInstructions):
    def __init__(self, environment_name, current_test_level: float, repeat: bool):
        super().__init__(CONTROL_TYPE, environment_name)
        self.current_test_level = current_test_level
        self.repeat = repeat

    def validate(self):
        return super().validate()


# endregion


# region Queues
class TimeQueues:
    """A set of queues used by the Time environment"""

    def __init__(
        self,
        environment_command_queue: VerboseMessageQueue,
        gui_update_queue: mp.queues.Queue,
        controller_communication_queue: VerboseMessageQueue,
        data_in_queue: mp.queues.Queue,
        data_out_queue: mp.queues.Queue,
        log_file_queue: VerboseMessageQueue,
    ):
        """
        Creates a namespace to store all the queues used by the Time Environment

        Parameters
        ----------
        environment_command_queue : VerboseMessageQueue
            Queue from which the environment will receive instructions.
        gui_update_queue : mp.queues.Queue
            Queue to which the environment will put GUI updates.
        controller_communication_queue : VerboseMessageQueue
            Queue to which the environment will put global contorller instructions.
        data_in_queue : mp.queues.Queue
            Queue from which the environment will receive data from acquisition.
        data_out_queue : mp.queues.Queue
            Queue to which the environment will write data for output.
        log_file_queue : VerboseMessageQueue
            Queue to which the environment will write log file messages.
        """
        self.environment_command_queue = environment_command_queue
        self.gui_update_queue = gui_update_queue
        self.controller_communication_queue = controller_communication_queue
        self.data_in_queue = data_in_queue
        self.data_out_queue = data_out_queue
        self.log_file_queue = log_file_queue


# endregion


# region Environment
class TimeEnvironment(Environment):
    """Environment defined by a generated time history signal"""

    def __init__(
        self,
        environment_name: str,
        queue_name: str,
        queue_container: TimeQueues,
        acquisition_active_event: mp.synchronize.Event,
        output_active_event: mp.synchronize.Event,
        active_event: mp.synchronize.Event,
        ready_event: mp.synchronize.Event,
    ):
        """
        Time History Generation Environment Constructor

        This function fills out the command map and initializes parameters to
        zero or null.

        Parameters
        ----------
        environment_name : str
            Name of the environment.
        queue_container : TimeQueues
            Container of queues used by the Time Environment.

        """
        super().__init__(
            environment_name,
            queue_name,
            queue_container.environment_command_queue,
            queue_container.gui_update_queue,
            queue_container.controller_communication_queue,
            queue_container.log_file_queue,
            queue_container.data_in_queue,
            queue_container.data_out_queue,
            acquisition_active_event,
            output_active_event,
            active_event,
            ready_event,
        )
        self.queue_container = queue_container
        # Define command map
        self.command_map[GlobalCommands.START_ENVIRONMENT] = self.run_environment
        self.command_map[TimeCommands.SET_TEST_LEVEL] = self.set_test_level
        self.command_map[TimeCommands.SET_NO_REPEAT] = self.set_no_repeat
        self.command_map[TimeCommands.SET_REPEAT] = self.set_repeat
        # Persistent data
        self.hardware_metadata = None
        self.metadata = None
        self.shutdown_flag = False
        self.current_test_level = 0.0
        self.target_test_level = 0.0
        self.test_level_change = 0.0
        self.repeat = False
        self.signal_remainder = None
        self.output_channels = None
        self.measurement_channels = None

    # endregion

    # region Commands
    def initialize_hardware(self, hardware_metadata: HardwareMetadata):
        """Initialize the data acquisition parameters in the environment.

        The environment will receive the global data acquisition parameters from
        the controller, and must set itself up accordingly.

        Parameters
        ----------
        hardware_metadata : HardwareMetadata :
            A container containing data acquisition parameters, including
            channels active in the environment as well as sampling parameters.
        """
        self.log("Initializing Data Acquisition Parameters")
        self.hardware_metadata = hardware_metadata
        self.measurement_channels = [
            index
            for index, channel in enumerate(self.hardware_metadata.channel_list)
            if channel.feedback_device is None
        ]
        self.output_channels = [
            index
            for index, channel in enumerate(self.hardware_metadata.channel_list)
            if channel.feedback_device is not None
        ]
        self.set_ready()

    def initialize_environment(self, metadata: TimeMetadata):
        """
        Initialize the environment parameters specific to this environment

        The environment will recieve parameters defining itself from the
        user interface and must set itself up accordingly.

        Parameters
        ----------
        metadata : TimeMetadata
            A container containing the parameters defining the environment

        """
        self.log("Initializing Environment Parameters")
        self.metadata = metadata
        self.set_ready()

    def run_environment(self, data):
        """Runs the time history environment.

        This function handles start up, running, and shutting down the environment

        During startup, the function will initialize a buffer that it will
        write from that consists of the output signal.

        When running, it will collect data that comes in from the ``data_in_queue``
        and tell the GUI to display it.  This will also tell
        the environment whether or not the signal is the last signal and that
        it should shut down.  The function determines if a
        new signal is required by checking if the data_out_queue is empty.
        If it is empty, we write the next portion of the buffer.
        If the buffer runs dry and the signal is not repeating, it will set the
        last_signal flag which tells the process to begin shutting down.  If
        shutdown is occuring, the process continues to get data until the last
        signal is received.

        Parameters
        ----------
        data : Tuple
            A tuple containing the test level to run the environment at and
            a boolean specifying whether or not to repeat the signal.

        """
        if not self.active:
            if data is not None:
                self.current_test_level = db2scale(data.current_test_level)
                self.repeat = data.repeat
                self.queue_container.gui_update_queue.put(
                    (
                        self.environment_name,
                        (UICommands.SET_ENVIRONMENT_INSTRUCTIONS, data),
                    )
                )
                self.log("Test Level set to {:}".format(self.current_test_level))
            self.signal_remainder = self.metadata.output_signal
            self.set_active()
            self.queue_container.gui_update_queue.put(
                (self.environment_name, (UICommands.ENVIRONMENT_STARTED, None))
            )
        # See if any data has come in
        try:
            acquisition_data, last_acquisition = (
                self.queue_container.data_in_queue.get_nowait()
            )
            measurement_data = acquisition_data[self.measurement_channels]
            output_data = acquisition_data[self.output_channels]
            self.queue_container.gui_update_queue.put(
                (
                    self.environment_name,
                    (TimeUICommands.TIME_DATA, (measurement_data, output_data)),
                )
            )
        except (thqueue.Empty, mpqueue.Empty):
            last_acquisition = False
        # See if we need to output data
        if self.queue_container.data_out_queue.empty():
            last_signal = False
            # See if there is enough in the remainder
            if (
                self.hardware_metadata.samples_per_write
                > self.signal_remainder.shape[-1]
                and self.repeat
            ):
                self.signal_remainder = np.concatenate(
                    (self.signal_remainder, self.metadata.output_signal), axis=-1
                )
            elif (
                self.hardware_metadata.samples_per_write
                >= self.signal_remainder.shape[-1]
                and not self.repeat
            ) or self.current_test_level == 0.0:
                last_signal = True
            self.output(
                self.signal_remainder[:, : self.hardware_metadata.samples_per_write],
                last_signal,
            )
            self.signal_remainder = self.signal_remainder[
                :, self.hardware_metadata.samples_per_write :
            ]
            if last_signal:
                # Wait until we get the last signal from the acquisition
                while not last_acquisition:
                    self.log("Waiting for Last Acquisition")
                    acquisition_data, last_acquisition = (
                        self.queue_container.data_in_queue.get()
                    )
                    measurement_data = acquisition_data[self.measurement_channels]
                    output_data = acquisition_data[self.output_channels]
                    self.queue_container.gui_update_queue.put(
                        (
                            self.environment_name,
                            (TimeUICommands.TIME_DATA, (measurement_data, output_data)),
                        )
                    )
                self.shutdown()
                return
        self.queue_container.environment_command_queue.put(
            self.environment_name, (GlobalCommands.START_ENVIRONMENT, None)
        )

    def output(self, write_data, last_signal=False):
        """Puts data to the data_out_queue and handles test level changes

        This function keeps track of the environment test level and scales the
        output signals accordingly prior to placing them into the data_out_queue.
        This function also handles the ramping between two test levels.

        Parameters
        ----------
        write_data : np.ndarray
            A numpy array containing the signals to be written.

        last_signal :
            Specifies if the signal being written is the last signal that will
            be generated due to the signal generation shutting down.  This is
            passed to the output task to tell it that there will be no more
            signals from this environment until it is restarted. (Default value
            = False)
        """
        # Perform the output transformation if necessary
        # Compute the test_level scaling for this dataset
        if self.test_level_change == 0.0:
            test_level = self.current_test_level
            self.log("Test Level at {:}".format(test_level))
        else:
            test_level = (
                self.current_test_level
                + (np.arange(write_data.shape[-1]) + 1) * self.test_level_change
            )
            # Compute distance in steps from the target test_level and find where it is near the target
            full_level_index = np.nonzero(
                abs(test_level - self.test_level_target) / abs(self.test_level_change)
                < TEST_LEVEL_THRESHOLD
            )[0]
            # Check if any are
            if len(full_level_index) > 0:
                # If so, set all test_levels after that one to the target test_level
                test_level[full_level_index[0] + 1 :] = self.test_level_target
                # And update that our current test_level is now the target test_level
                self.current_test_level = self.test_level_target
                self.test_level_change = 0.0
            else:
                # Otherwise, our current test_level is the last entry in the test_level scaling
                self.current_test_level = test_level[-1]
            self.log("Test level from {:} to {:}".format(test_level[0], test_level[-1]))
        # Write the test level-scaled data to the task
        self.log("Sending data to data_out queue")
        self.queue_container.data_out_queue.put(
            (copy.deepcopy(write_data * test_level), last_signal)
        )

    def set_test_level(self, data):
        level = db2scale(data)
        self.adjust_test_level(level)
        self.queue_container.gui_update_queue.put(
            (self.environment_name, (TimeCommands.SET_TEST_LEVEL, data))
        )

    def set_no_repeat(self, data=None):
        self.repeat = False
        self.log("Repeat turned off")
        self.queue_container.gui_update_queue.put(
            (self.environment_name, (TimeCommands.SET_NO_REPEAT, data))
        )

    def set_repeat(self, data=None):
        self.repeat = True
        self.log("Repeat turned on")
        self.queue_container.gui_update_queue.put(
            (self.environment_name, (TimeCommands.SET_REPEAT, data))
        )

    def stop_environment(self, data):
        """Stops the environment by setting the test level to zero.

        Parameters
        ----------
        data : Ignored
            This parameter is not used by the function but is required for the
            ``command_map`` calling signature.

        """
        self.adjust_test_level(0.0)

    def adjust_test_level(self, data):
        """Adjusts the test level of the signal

        Parameters
        ----------
        data :
            New target test level

        """
        self.test_level_target = data
        self.test_level_change = (
            self.test_level_target - self.current_test_level
        ) / self.metadata.cancel_rampdown_samples
        if self.test_level_change != 0.0:
            self.log(
                "Changed test level to {:} from {:}, {:} change per sample".format(
                    self.test_level_target,
                    self.current_test_level,
                    self.test_level_change,
                )
            )

    # endregion

    # region Shutdown
    def shutdown(self):
        """Performs final cleanup operations when the system has shut down

        This function is called when the environment has been instructed
        to shut down and the last acquisition data has been received.  The signal generation
        is the first process in the Random Vibration environment to stop when
        shutdown is called, so it notifies the environment process to stop the
        acquisition and analysis tasks because it is no longer generating signals

        """
        self.log("Shutting Down Time History Generation")
        self.queue_container.environment_command_queue.flush(self.environment_name)
        # Enable the volume controls
        self.clear_active()
        self.queue_container.gui_update_queue.put(
            (self.environment_name, (UICommands.ENVIRONMENT_ENDED, None))
        )

    # endregion


# region: time_process
def time_process(
    environment_name: str,
    queue_name: str,
    input_queue: VerboseMessageQueue,
    gui_update_queue: mp.Queue,
    controller_command_queue: VerboseMessageQueue,
    log_file_queue: mp.Queue,
    data_in_queue: mp.Queue,
    data_out_queue: mp.Queue,
    acquisition_active_event: mp.synchronize.Event,
    output_active_event: mp.synchronize.Event,
    active_event: mp.synchronize.Event,
    ready_event: mp.synchronize.Event,
    shutdown_event: mp.synchronize.Event,
    sysid_event: mp.synchronize.Event,
    threaded: bool,
):
    """Time signal generation environment process function called by multiprocessing

    This function defines the environment process that
    gets run by the multiprocessing module when it creates a new process.  It
    creates a TimeEnviornment object and runs it.

    Parameters
    ----------
    environment_name : str :
        Name of the environment
    input_queue : VerboseMessageQueue :
        Queue containing instructions for the environment
    gui_update_queue : Queue :
        Queue where GUI updates are put
    controller_command_queue : Queue :
        Queue for global communications with the controller
    log_file_queue : Queue :
        Queue for writing log file messages
    data_in_queue : Queue :
        Queue from which data will be read by the environment
    data_out_queue : Queue :
        Queue to which data will be written that will be output by the hardware.

    """

    # Create vibration queues
    queue_container = TimeQueues(
        input_queue,
        gui_update_queue,
        controller_command_queue,
        data_in_queue,
        data_out_queue,
        log_file_queue,
    )

    process_class = TimeEnvironment(
        environment_name,
        queue_name,
        queue_container,
        acquisition_active_event,
        output_active_event,
        active_event,
        ready_event,
    )
    process_class.run(shutdown_event)
